### ISSUE TITLE
Remove unmaintained version

### ISSUE THREAD

**Issue by AsriFox** [IvanNovak1004/gnuradio-integration#1]
Hello. I've created a [fork](https://github.com/AsriFox/vscode-gnuradio-integration) of this repository and added GNURadio ModTool functionality to the extension. I'd like to publish it to the Visual Studio Marketplace, but [this extension](https://marketplace.visualstudio.com/items?itemName=ivannovak1004.gnuradio-integration) is still there. Please, either remove it or signal that you will publish updates yourself so that I would open a PR.

**Comment by IvanNovak1004** [comment]
Hello. Thanks for the notice and contribution, please create a pull request. I will publish updates.

**Comment by AsriFox** [comment]
Are you planning on publishing the extension to [Open VSX Registry](https://open-vsx.org) for VSCodium users?

**Comment by IvanNovak1004** [comment]
Hello Oleg. I just published new version. I am not planning to publish Open VSX Registry. Feel free to take over the extension from me, my project with gnuradio is finished and I do not plan work on it soon. Just ping me when you will have next release. I'll remove it and then do what you want. I am not sure If i could add you somehow as contributor to vscode marketplace account.
